# filepath: alembic/script.py.mako
"""initial schema

Revision ID: 494d357f8dfd
Revises: 
Create Date: 2026-01-17 06:43:34.148880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494d357f8dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('deriv_account_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('app_markup_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deriv_account_id'), 'users', ['deriv_account_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('stake_amount', sa.Float(), nullable=False),
    sa.Column('gross_payout', sa.Float(), nullable=True),
    sa.Column('markup_percentage', sa.Float(), nullable=False),
    sa.Column('markup_amount', sa.Float(), nullable=False),
    sa.Column('net_payout', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trade_amount', sa.Float(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('contract_duration', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('max_trades', sa.Integer(), nullable=False),
    sa.Column('max_trades_per_hour', sa.Integer(), nullable=False),
    sa.Column('daily_loss_limit_pct', sa.Float(), nullable=False),
    sa.Column('daily_profit_limit_pct', sa.Float(), nullable=False),
    sa.Column('cooldown_after_loss', sa.Integer(), nullable=False),
    sa.Column('cooldown_after_win', sa.Integer(), nullable=False),
    sa.Column('recovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('recovery_mode', sa.Enum('MARTINGALE', 'FIBONACCI', 'HYBRID', name='recoverymode'), nullable=False),
    sa.Column('recovery_multiplier', sa.Float(), nullable=False),
    sa.Column('max_recovery_streak', sa.Integer(), nullable=False),
    sa.Column('max_recovery_amount_multiplier', sa.Float(), nullable=False),
    sa.Column('reset_on_win', sa.Boolean(), nullable=False),
    sa.Column('smart_recovery', sa.Boolean(), nullable=False),
    sa.Column('min_consensus_score', sa.Float(), nullable=False),
    sa.Column('ml_consensus_enabled', sa.Boolean(), nullable=False),
    sa.Column('strategy_optimization_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_on_trade', sa.Boolean(), nullable=False),
    sa.Column('email_on_loss', sa.Boolean(), nullable=False),
    sa.Column('email_on_daily_limit', sa.Boolean(), nullable=False),
    sa.Column('push_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('chart_type', sa.String(), nullable=False),
    sa.Column('auto_refresh_enabled', sa.Boolean(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('commissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('markup_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('entry_tick', sa.Float(), nullable=True),
    sa.Column('exit_tick', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('markup_profit', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('sell_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('audit_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_trade_id'), 'contracts', ['trade_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals')
    op.drop_index(op.f('ix_contracts_trade_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deriv_account_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###